# Generated by Django 2.1 on 2018-08-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.CharField(blank='True', max_length=100, verbose_name='description')),
                ('content', models.TextField(verbose_name='content')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create_date')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='modify_date')),
            ],
        ),
    ]
